### ISSUE TITLE
Type error when using strict package manager

### ISSUE THREAD

**Issue by Methuselah96** [syntax-tree/hast-util-raw#20]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hast-util-raw@8.0.0 and hast-util-raw@9.0.0

Looks like the reference to `@types/unist` was introduced in https://github.com/syntax-tree/hast-util-raw/pull/17.

### Steps to reproduce

1. Create project using `hast-util-raw` with a strict package manager like Yarn PnP and `skipLibCheck` set to `false`.
2. Type-check using TypeScript.

### Expected behavior

No type errors.

### Actual behavior

Type error:

```
ERROR in node_modules/hast-util-raw/lib/index.d.ts:28:28
TS2307: Cannot find module 'unist' or its corresponding type declarations.
    26 | export type Location = import('parse5').Token.Location;
    27 | export type TagToken = import('parse5').Token.TagToken;
  > 28 | export type Point = import('unist').Point;
       |                            ^^^^^^^
    29 | export type VFile = import('vfile').VFile;
    30 | /**
    31 |  * Configuration.
```

### Affected runtime and version

N/A

**Comment by remcohaszing** [comment]
You’re right, this should be an explicit dependency. Would you like to add a PR for this?

**Comment by wooorm** [comment]
https://github.com/syntax-tree/hast-util-raw/releases/tag/9.0.1
